[book]
authors = ["Yatagarasu Team"]
language = "en"
multilingual = false
src = "src"
title = "Yatagarasu Documentation"

[build]
build-dir = "book"

[output.html]
git-repository-url = "https://github.com/julianshen/yatagarasu"
edit-url-template = "https://github.com/julianshen/yatagarasu/edit/master/docs-site/src/{path}"
site-url = "/yatagarasu/"
