apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: yatagarasu-loadtest

resources:
  - namespace.yaml
  - minio.yaml
  - yatagarasu.yaml
  - tests.yaml

commonLabels:
  app.kubernetes.io/part-of: yatagarasu-loadtest
