apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

metadata:
  name: yatagarasu-prod

namespace: yatagarasu

namePrefix: prod-

commonLabels:
  environment: production

resources:
  - ../../base
  - pdb.yaml

patches:
  - path: deployment-patch.yaml

configMapGenerator:
  - name: yatagarasu-config
    behavior: replace
    files:
      - config.yaml

images:
  - name: ghcr.io/julianshen/yatagarasu
    newTag: "1.3.0"
